Get http://localhost:3000


### Get all contacts
GET http://localhost:3000/users

###

### Get a specific contact by ID
GET http://localhost:3000/users/687f8fea63833a8948035904

###

### Create a new contact
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "firstName":"Gregor",
  "lastName":"Tiwauke",
  "email":"GTiwauke@test.com",
  "nationality":"American Indian",
  "birthday":"12/12/18",
  "address":"123 Main St, San Diego, California, USA",
  "phone":"485-689-5524"
}

###

### Update an existing contact by ID
PUT http://localhost:3000/users/687f8fea63833a8948035904
Content-Type: application/json

{
  "firstName":"Gregor",
  "lastName":"Tiwauke",
  "email":"GTiwauke@test.com",
  "nationality":"American Indian",
  "birthday":"12/12/18",
  "address":"123 Main St, San Diego, California, USA",
  "phone":"485-689-5524"
}

###

### Delete a contact (example)
DELETE http://localhost:3000/users/687f8fea63833a8948035904
